// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EasyDialog: typeof import('./../src/components/EasyDialog/index.vue')['default'];
    EasyForm: typeof import('./../src/components/EasyForm/index.vue')['default'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    Footer: typeof import('./../src/components/Footer/index.vue')['default'];
    Header: typeof import('./../src/components/Header/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default'];
    Table: typeof import('./../src/components/Table/index.vue')['default'];
    TableColumn: typeof import('./../src/components/Table/TableColumn.vue')['default'];
  }
}
