server:
  port: 10000

spring:
  redis:
    host: nas.titxu.com
    port: 6379
    password: lxue0422
    database: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          # 获取JWT验签公钥请求路径
          jwk-set-uri: 'http://localhost:8000/getPublicKey'
  cloud:
    nacos:
      discovery:
        server-addr: nas.titxu.com:8848
    sentinel:
      transport:
        dashboard: localhost:5003
    gateway:
      routes:
      # 认证中心
      - id: titxu-server-auth
        uri: lb://titxu-server-auth
        predicates:
        - Path=/auth/**
      # 用户
      - id: titxu-server-sys
        uri: lb://titxu-server-sys
        predicates:
        - Path=/sys/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

# 配置白名单路径
white-list:
  urls:
  - "/auth/**"
  - "/actuator/**"
  - "/v2/api-docs/**"
  - "/assets/**"
  - "/sys/captcha"
  - "/sys/register/**"