server:
  port: 8000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lxue0422
    url: jdbc:mysql://nas.titxu.com:5555/titxu-cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    host: nas.titxu.com
    port: 6379
    password: lxue0422
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: nas.titxu.com:8848
    sentinel:
      transport:
        dashboard: localhost:5003